# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  pull_request:
    types: [labeled]
name: Deploy
env:
  SERVICE: ${GITHUB_REPOSITORY##*/}
  TARGET_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/$SERVICE:${GITHUB_SHA::7}
jobs:
  deploy:
    if: github.event.label.name == 'deploy'
    name: Push to Cluster
    runs-on: ubuntu-latest
    env:
      CLUSTER_REPO: my_project/k8s_dev
    steps:
      - name: Kustomized Namespace - Create Overlay
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: zyngl/create_kustomized_namespace@v1.3.0
        with:
          args: --flux
